#!/bin/bash

cd /usr/share/apache2/empower.me/data/aemo-json/script

/usr/bin/python /usr/share/apache2/empower.me/data/aemo-json/script/extract-forecast-7day.py > /usr/share/apache2/empower.me/data/aemo-json/log/forecast.txt
